SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

COLOR_FOREGROUND = "white"

PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

TOUCH_CONTROL_MARGIN = 40
TOUCH_JOYSTICK_RADIUS = 100
TOUCH_JOYSTICK_KNOB_RADIUS = 40
TOUCH_JOYSTICK_DEAD_ZONE = 0.15
TOUCH_FIRE_BUTTON_SIZE = 120

TOUCH_CONTROL_COLOR = (180, 180, 180)
TOUCH_CONTROL_TEXT_COLOR = COLOR_FOREGROUND

TOUCH_CONTROLS_TOGGLE_MARGIN = 16
TOUCH_CONTROLS_TOGGLE_WIDTH = 210
TOUCH_CONTROLS_TOGGLE_HEIGHT = 44
TOUCH_CONTROLS_TOGGLE_BG_COLOR = (30, 30, 30)
TOUCH_CONTROLS_TOGGLE_BORDER_COLOR = TOUCH_CONTROL_COLOR
HUD_BAR_HEIGHT = 60
HUD_BAR_BG_COLOR = (95, 95, 95, 200)
PLAYFIELD_TOP = HUD_BAR_HEIGHT
PLAYFIELD_BOTTOM = SCREEN_HEIGHT
PLAYFIELD_HEIGHT = PLAYFIELD_BOTTOM - PLAYFIELD_TOP

# High-score / player identity
GAME_STATS_FILE = "asteroids_stats.json"
GAME_STATS_ROW_ID = "global"
HIGH_SCORES_FILE = "asteroids_high_scores.json"
HIGH_SCORES_MAX_ENTRIES = 10
HIGH_SCORES_DISPLAY_ENTRIES = 5
PLAYER_NAME_MAX_LENGTH = 24

# Shared leaderboard (Supabase)
# - Set these to enable a global high-score table for the web build.
# - The anon key is OK to expose in a browser app.
SUPABASE_URL = "https://jcqwpaoqyubjlldcbkwu.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcXdwYW9xeXViamxsZGNia3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MDY1NjAsImV4cCI6MjA5NTM4MjU2MH0.62luJa8OimEczbS5_sSVKdfc9XNQWtSPdeoiETP6NN4"
SUPABASE_HIGH_SCORES_TABLE = "asteroids_high_scores"
SUPABASE_STATS_TABLE = "asteroids_stats"
