SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

COLOR_FOREGROUND = "white"

PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

TOUCH_CONTROL_MARGIN = 40
TOUCH_JOYSTICK_RADIUS = 100
TOUCH_JOYSTICK_KNOB_RADIUS = 40
TOUCH_JOYSTICK_DEAD_ZONE = 0.15
TOUCH_FIRE_BUTTON_SIZE = 120

TOUCH_CONTROL_COLOR = (180, 180, 180)
TOUCH_CONTROL_TEXT_COLOR = COLOR_FOREGROUND

TOUCH_CONTROLS_TOGGLE_MARGIN = 16
TOUCH_CONTROLS_TOGGLE_WIDTH = 210
TOUCH_CONTROLS_TOGGLE_HEIGHT = 44
TOUCH_CONTROLS_TOGGLE_BG_COLOR = (30, 30, 30)
TOUCH_CONTROLS_TOGGLE_BORDER_COLOR = TOUCH_CONTROL_COLOR
