-- Run once in the Supabase SQL editor for the shared high-score leaderboard.

create table if not exists public.asteroids_high_scores (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null,
  created_at timestamptz not null default now()
);

create index if not exists asteroids_high_scores_rank_idx
  on public.asteroids_high_scores (score desc, created_at desc);

alter table public.asteroids_high_scores enable row level security;

create policy "asteroids_high_scores_select"
  on public.asteroids_high_scores for select
  using (true);

create policy "asteroids_high_scores_insert"
  on public.asteroids_high_scores for insert
  with check (
    length(name) between 1 and 12
    and score between 0 and 1000000
  );

